services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./utils/recipes/Dockerfile_client
    tty: true
    volumes:
      - ./utils/storage/client/Taskfile.yaml:/root/Taskfile.yaml
  secured-server:
    container_name: secured-server
    build:
      context: .
      dockerfile: ./utils/recipes/Dockerfile_server
    volumes:
      - .:/app
    ports:
      - "8002:80"
    environment:
      - SERVER_NAME=:80
  database:
    container_name: edu-web-database
    image: mariadb:10.5.8
#    image: mysql:8.0
#    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
#    platform: linux/amd64
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: studoo
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      #MYSQL_USER: app_db_user
      #MYSQL_PASSWORD: app_db_password
    volumes:
      - ./var/dbdata:/var/lib/mysql
      - ./docs/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    container_name: edu-web-pma
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - database
#  mailer:
#    container_name: edu-web-mailer
#    image: schickling/mailcatcher
#    ports: [ "1025:1025", "1080:1080" ]
volumes:
  dbdata: